server:
  port: 2002
#  servlet:
#    context-path: /content

spring:
  application:
    name: mall-market
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #      url: jdbc:mysql://10.0.93.60:3306/mall_demo?useUnicode=true&characterEncoding=utf8
      url: jdbc:mysql://localhost:3306/mall_demo?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      initial-size: 1
      max-active: 20
      max-wait: 30000
      min-idle: 1
      time-between-eviction-runs-millis: 50000
      min-evictable-idle-time-millis: 50000
      validation-query: select 1 from dual
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter: stat,wall
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

#security
auth-server: http://localhost:2001/oauth
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: ${auth-server}/token
      user-authorization-uri: ${auth-server}/authorize
    resource:
      token-info-uri: ${auth-server}/check_token
